github.com:
    users:
        rrushikeshp69:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: rrushikeshp69
